language: ruby
rvm:
- 2.3.3
bundler_args: --without development
script: bundle exec rake github_pages
env:
  global:
  - secure: bovxRIGjsIxero8nPtbdb30Hkhk1rhoEkO879+ZAdaVbYvex66Ou+bLGIU3TjN0jN5Ljs2XSPFxOhW1PkpXcEEYr7j36HRHuRBwbC5oBstyt+4x4x7QAh4pVctKG4vFMZSMBboaxfktNiFdrMJfs+8qbmcEmMgsUuL90LRCLZSkjUL48Njqo548Z1FqPihkR0fQXHJMncE1hw7ABZ2XQ3NE/V3SKMCcgSDVP0QkfKckNt4KTGWvjxKdR2cP+w99k8pA1sNeeBs/9r+Xjt61XFE+k7xW2R5VLBFGDt4rRigIFxRih4Z0/IM3aoyuK9yoxEa0D980mPLvXFgps3j6rLQc7cypzSJ3olAxp3PtgiKX+xCrxOcdKWkz9TYZcA75VA0wTUkQuJhGCEFgLf4S2U5whCWioAQ4bLtqM5uOJrU/x7kpvj1PVLSrMsc6G4t8Z63ZF3M0+zqAzrnerafOsO79Aopcy22qzlfwCiZdPnzjIWDcN+eSW0lecfB2N7ORqj5OwizYjb/6Isw3hugBYn//IwW0vcNIZF+mW4CPjEISNinzG7e35w5JzdmlwAnQocreO8LMLVmIJD/DIxvEWQXt9IBp6/YwDcOT0O8J/D6mlFa83o/eVkICEQInHMX9RyYHGp1sbm5lcdb24qcGfI/rQ3LtJVLvjma6rVyD3AbQ=
